/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingEventsRouteImport } from './routes/upcoming-events'
import { Route as TimeTableBatchOf202324RouteImport } from './routes/time-table-batch-of-2023-24'
import { Route as TheRouteImport } from './routes/the'
import { Route as Tedx1RouteImport } from './routes/tedx1'
import { Route as TedxRouteImport } from './routes/tedx'
import { Route as TeamConventionRouteImport } from './routes/team-convention'
import { Route as SynergyRouteImport } from './routes/synergy'
import { Route as SymposiaRouteImport } from './routes/symposia'
import { Route as StudentBodyRouteImport } from './routes/student-body'
import { Route as SportsCellRouteImport } from './routes/sports-cell'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RavenbrainRouteImport } from './routes/ravenbrain'
import { Route as ProspectiveRecruitersRouteImport } from './routes/prospective-recruiters'
import { Route as ProgrammeBrochureRouteImport } from './routes/programme-brochure'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as NewslettersRouteImport } from './routes/newsletters'
import { Route as MediaCoverageFormRouteImport } from './routes/media-coverage-form'
import { Route as MediaAndPrCellRouteImport } from './routes/media-and-pr-cell'
import { Route as MarcomCellRouteImport } from './routes/marcom-cell'
import { Route as LinkinbioRouteImport } from './routes/linkinbio'
import { Route as IisacRouteImport } from './routes/iisac'
import { Route as IbCellRouteImport } from './routes/ib-cell'
import { Route as FinanceCellRouteImport } from './routes/finance-cell'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as Erudition1RouteImport } from './routes/erudition1'
import { Route as EruditionTestimonialsRouteImport } from './routes/erudition-testimonials'
import { Route as EruditionRouteImport } from './routes/erudition'
import { Route as EcclesiaRouteImport } from './routes/ecclesia'
import { Route as DiscoRouteImport } from './routes/disco'
import { Route as CorporateRelationsTeamRouteImport } from './routes/corporate-relations-team'
import { Route as CopyOfUpcomingEventsRouteImport } from './routes/copy-of-upcoming-events'
import { Route as CopyOfMarcomCellRouteImport } from './routes/copy-of-marcom-cell'
import { Route as CopyOfHomeRouteImport } from './routes/copy-of-home'
import { Route as CopyOfEruditionRouteImport } from './routes/copy-of-erudition'
import { Route as CopyOfBatch20242026RouteImport } from './routes/copy-of-batch-2024-2026'
import { Route as CopyOfBatch20232025RouteImport } from './routes/copy-of-batch-2023-2025'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as Batch20232025RouteImport } from './routes/batch-2023-2025'
import { Route as Batch20222024RouteImport } from './routes/batch-2022-2024'
import { Route as Batch20212023RouteImport } from './routes/batch-2021-2023'
import { Route as Batch20202022RouteImport } from './routes/batch-2020-2022'
import { Route as AlumniDinnerRouteImport } from './routes/alumni-dinner'
import { Route as AlumniCommitteeRouteImport } from './routes/alumni-committee'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as Admissions1RouteImport } from './routes/admissions-1'
import { Route as AdmissionListsRouteImport } from './routes/admission-lists'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsTestBlogRouteImport } from './routes/posts.test-blog'

const UpcomingEventsRoute = UpcomingEventsRouteImport.update({
  id: '/upcoming-events',
  path: '/upcoming-events',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTableBatchOf202324Route = TimeTableBatchOf202324RouteImport.update({
  id: '/time-table-batch-of-2023-24',
  path: '/time-table-batch-of-2023-24',
  getParentRoute: () => rootRouteImport,
} as any)
const TheRoute = TheRouteImport.update({
  id: '/the',
  path: '/the',
  getParentRoute: () => rootRouteImport,
} as any)
const Tedx1Route = Tedx1RouteImport.update({
  id: '/tedx1',
  path: '/tedx1',
  getParentRoute: () => rootRouteImport,
} as any)
const TedxRoute = TedxRouteImport.update({
  id: '/tedx',
  path: '/tedx',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamConventionRoute = TeamConventionRouteImport.update({
  id: '/team-convention',
  path: '/team-convention',
  getParentRoute: () => rootRouteImport,
} as any)
const SynergyRoute = SynergyRouteImport.update({
  id: '/synergy',
  path: '/synergy',
  getParentRoute: () => rootRouteImport,
} as any)
const SymposiaRoute = SymposiaRouteImport.update({
  id: '/symposia',
  path: '/symposia',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentBodyRoute = StudentBodyRouteImport.update({
  id: '/student-body',
  path: '/student-body',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsCellRoute = SportsCellRouteImport.update({
  id: '/sports-cell',
  path: '/sports-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RavenbrainRoute = RavenbrainRouteImport.update({
  id: '/ravenbrain',
  path: '/ravenbrain',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectiveRecruitersRoute = ProspectiveRecruitersRouteImport.update({
  id: '/prospective-recruiters',
  path: '/prospective-recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeBrochureRoute = ProgrammeBrochureRouteImport.update({
  id: '/programme-brochure',
  path: '/programme-brochure',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersRoute = NewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCoverageFormRoute = MediaCoverageFormRouteImport.update({
  id: '/media-coverage-form',
  path: '/media-coverage-form',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaAndPrCellRoute = MediaAndPrCellRouteImport.update({
  id: '/media-and-pr-cell',
  path: '/media-and-pr-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcomCellRoute = MarcomCellRouteImport.update({
  id: '/marcom-cell',
  path: '/marcom-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkinbioRoute = LinkinbioRouteImport.update({
  id: '/linkinbio',
  path: '/linkinbio',
  getParentRoute: () => rootRouteImport,
} as any)
const IisacRoute = IisacRouteImport.update({
  id: '/iisac',
  path: '/iisac',
  getParentRoute: () => rootRouteImport,
} as any)
const IbCellRoute = IbCellRouteImport.update({
  id: '/ib-cell',
  path: '/ib-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceCellRoute = FinanceCellRouteImport.update({
  id: '/finance-cell',
  path: '/finance-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const Erudition1Route = Erudition1RouteImport.update({
  id: '/erudition1',
  path: '/erudition1',
  getParentRoute: () => rootRouteImport,
} as any)
const EruditionTestimonialsRoute = EruditionTestimonialsRouteImport.update({
  id: '/erudition-testimonials',
  path: '/erudition-testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const EruditionRoute = EruditionRouteImport.update({
  id: '/erudition',
  path: '/erudition',
  getParentRoute: () => rootRouteImport,
} as any)
const EcclesiaRoute = EcclesiaRouteImport.update({
  id: '/ecclesia',
  path: '/ecclesia',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoRoute = DiscoRouteImport.update({
  id: '/disco',
  path: '/disco',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRelationsTeamRoute = CorporateRelationsTeamRouteImport.update({
  id: '/corporate-relations-team',
  path: '/corporate-relations-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyOfUpcomingEventsRoute = CopyOfUpcomingEventsRouteImport.update({
  id: '/copy-of-upcoming-events',
  path: '/copy-of-upcoming-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyOfMarcomCellRoute = CopyOfMarcomCellRouteImport.update({
  id: '/copy-of-marcom-cell',
  path: '/copy-of-marcom-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyOfHomeRoute = CopyOfHomeRouteImport.update({
  id: '/copy-of-home',
  path: '/copy-of-home',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyOfEruditionRoute = CopyOfEruditionRouteImport.update({
  id: '/copy-of-erudition',
  path: '/copy-of-erudition',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyOfBatch20242026Route = CopyOfBatch20242026RouteImport.update({
  id: '/copy-of-batch-2024-2026',
  path: '/copy-of-batch-2024-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyOfBatch20232025Route = CopyOfBatch20232025RouteImport.update({
  id: '/copy-of-batch-2023-2025',
  path: '/copy-of-batch-2023-2025',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const Batch20232025Route = Batch20232025RouteImport.update({
  id: '/batch-2023-2025',
  path: '/batch-2023-2025',
  getParentRoute: () => rootRouteImport,
} as any)
const Batch20222024Route = Batch20222024RouteImport.update({
  id: '/batch-2022-2024',
  path: '/batch-2022-2024',
  getParentRoute: () => rootRouteImport,
} as any)
const Batch20212023Route = Batch20212023RouteImport.update({
  id: '/batch-2021-2023',
  path: '/batch-2021-2023',
  getParentRoute: () => rootRouteImport,
} as any)
const Batch20202022Route = Batch20202022RouteImport.update({
  id: '/batch-2020-2022',
  path: '/batch-2020-2022',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniDinnerRoute = AlumniDinnerRouteImport.update({
  id: '/alumni-dinner',
  path: '/alumni-dinner',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniCommitteeRoute = AlumniCommitteeRouteImport.update({
  id: '/alumni-committee',
  path: '/alumni-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const Admissions1Route = Admissions1RouteImport.update({
  id: '/admissions-1',
  path: '/admissions-1',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionListsRoute = AdmissionListsRouteImport.update({
  id: '/admission-lists',
  path: '/admission-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsTestBlogRoute = PostsTestBlogRouteImport.update({
  id: '/posts/test-blog',
  path: '/posts/test-blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission-lists': typeof AdmissionListsRoute
  '/admissions-1': typeof Admissions1Route
  '/alumni': typeof AlumniRoute
  '/alumni-committee': typeof AlumniCommitteeRoute
  '/alumni-dinner': typeof AlumniDinnerRoute
  '/batch-2020-2022': typeof Batch20202022Route
  '/batch-2021-2023': typeof Batch20212023Route
  '/batch-2022-2024': typeof Batch20222024Route
  '/batch-2023-2025': typeof Batch20232025Route
  '/blog': typeof BlogRoute
  '/copy-of-batch-2023-2025': typeof CopyOfBatch20232025Route
  '/copy-of-batch-2024-2026': typeof CopyOfBatch20242026Route
  '/copy-of-erudition': typeof CopyOfEruditionRoute
  '/copy-of-home': typeof CopyOfHomeRoute
  '/copy-of-marcom-cell': typeof CopyOfMarcomCellRoute
  '/copy-of-upcoming-events': typeof CopyOfUpcomingEventsRoute
  '/corporate-relations-team': typeof CorporateRelationsTeamRoute
  '/disco': typeof DiscoRoute
  '/ecclesia': typeof EcclesiaRoute
  '/erudition': typeof EruditionRoute
  '/erudition-testimonials': typeof EruditionTestimonialsRoute
  '/erudition1': typeof Erudition1Route
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/finance-cell': typeof FinanceCellRoute
  '/ib-cell': typeof IbCellRoute
  '/iisac': typeof IisacRoute
  '/linkinbio': typeof LinkinbioRoute
  '/marcom-cell': typeof MarcomCellRoute
  '/media-and-pr-cell': typeof MediaAndPrCellRoute
  '/media-coverage-form': typeof MediaCoverageFormRoute
  '/newsletters': typeof NewslettersRoute
  '/placements': typeof PlacementsRoute
  '/programme-brochure': typeof ProgrammeBrochureRoute
  '/prospective-recruiters': typeof ProspectiveRecruitersRoute
  '/ravenbrain': typeof RavenbrainRoute
  '/registration': typeof RegistrationRoute
  '/sports-cell': typeof SportsCellRoute
  '/student-body': typeof StudentBodyRoute
  '/symposia': typeof SymposiaRoute
  '/synergy': typeof SynergyRoute
  '/team-convention': typeof TeamConventionRoute
  '/tedx': typeof TedxRoute
  '/tedx1': typeof Tedx1Route
  '/the': typeof TheRoute
  '/time-table-batch-of-2023-24': typeof TimeTableBatchOf202324Route
  '/upcoming-events': typeof UpcomingEventsRoute
  '/posts/test-blog': typeof PostsTestBlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission-lists': typeof AdmissionListsRoute
  '/admissions-1': typeof Admissions1Route
  '/alumni': typeof AlumniRoute
  '/alumni-committee': typeof AlumniCommitteeRoute
  '/alumni-dinner': typeof AlumniDinnerRoute
  '/batch-2020-2022': typeof Batch20202022Route
  '/batch-2021-2023': typeof Batch20212023Route
  '/batch-2022-2024': typeof Batch20222024Route
  '/batch-2023-2025': typeof Batch20232025Route
  '/blog': typeof BlogRoute
  '/copy-of-batch-2023-2025': typeof CopyOfBatch20232025Route
  '/copy-of-batch-2024-2026': typeof CopyOfBatch20242026Route
  '/copy-of-erudition': typeof CopyOfEruditionRoute
  '/copy-of-home': typeof CopyOfHomeRoute
  '/copy-of-marcom-cell': typeof CopyOfMarcomCellRoute
  '/copy-of-upcoming-events': typeof CopyOfUpcomingEventsRoute
  '/corporate-relations-team': typeof CorporateRelationsTeamRoute
  '/disco': typeof DiscoRoute
  '/ecclesia': typeof EcclesiaRoute
  '/erudition': typeof EruditionRoute
  '/erudition-testimonials': typeof EruditionTestimonialsRoute
  '/erudition1': typeof Erudition1Route
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/finance-cell': typeof FinanceCellRoute
  '/ib-cell': typeof IbCellRoute
  '/iisac': typeof IisacRoute
  '/linkinbio': typeof LinkinbioRoute
  '/marcom-cell': typeof MarcomCellRoute
  '/media-and-pr-cell': typeof MediaAndPrCellRoute
  '/media-coverage-form': typeof MediaCoverageFormRoute
  '/newsletters': typeof NewslettersRoute
  '/placements': typeof PlacementsRoute
  '/programme-brochure': typeof ProgrammeBrochureRoute
  '/prospective-recruiters': typeof ProspectiveRecruitersRoute
  '/ravenbrain': typeof RavenbrainRoute
  '/registration': typeof RegistrationRoute
  '/sports-cell': typeof SportsCellRoute
  '/student-body': typeof StudentBodyRoute
  '/symposia': typeof SymposiaRoute
  '/synergy': typeof SynergyRoute
  '/team-convention': typeof TeamConventionRoute
  '/tedx': typeof TedxRoute
  '/tedx1': typeof Tedx1Route
  '/the': typeof TheRoute
  '/time-table-batch-of-2023-24': typeof TimeTableBatchOf202324Route
  '/upcoming-events': typeof UpcomingEventsRoute
  '/posts/test-blog': typeof PostsTestBlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission-lists': typeof AdmissionListsRoute
  '/admissions-1': typeof Admissions1Route
  '/alumni': typeof AlumniRoute
  '/alumni-committee': typeof AlumniCommitteeRoute
  '/alumni-dinner': typeof AlumniDinnerRoute
  '/batch-2020-2022': typeof Batch20202022Route
  '/batch-2021-2023': typeof Batch20212023Route
  '/batch-2022-2024': typeof Batch20222024Route
  '/batch-2023-2025': typeof Batch20232025Route
  '/blog': typeof BlogRoute
  '/copy-of-batch-2023-2025': typeof CopyOfBatch20232025Route
  '/copy-of-batch-2024-2026': typeof CopyOfBatch20242026Route
  '/copy-of-erudition': typeof CopyOfEruditionRoute
  '/copy-of-home': typeof CopyOfHomeRoute
  '/copy-of-marcom-cell': typeof CopyOfMarcomCellRoute
  '/copy-of-upcoming-events': typeof CopyOfUpcomingEventsRoute
  '/corporate-relations-team': typeof CorporateRelationsTeamRoute
  '/disco': typeof DiscoRoute
  '/ecclesia': typeof EcclesiaRoute
  '/erudition': typeof EruditionRoute
  '/erudition-testimonials': typeof EruditionTestimonialsRoute
  '/erudition1': typeof Erudition1Route
  '/facilities': typeof FacilitiesRoute
  '/faqs': typeof FaqsRoute
  '/finance-cell': typeof FinanceCellRoute
  '/ib-cell': typeof IbCellRoute
  '/iisac': typeof IisacRoute
  '/linkinbio': typeof LinkinbioRoute
  '/marcom-cell': typeof MarcomCellRoute
  '/media-and-pr-cell': typeof MediaAndPrCellRoute
  '/media-coverage-form': typeof MediaCoverageFormRoute
  '/newsletters': typeof NewslettersRoute
  '/placements': typeof PlacementsRoute
  '/programme-brochure': typeof ProgrammeBrochureRoute
  '/prospective-recruiters': typeof ProspectiveRecruitersRoute
  '/ravenbrain': typeof RavenbrainRoute
  '/registration': typeof RegistrationRoute
  '/sports-cell': typeof SportsCellRoute
  '/student-body': typeof StudentBodyRoute
  '/symposia': typeof SymposiaRoute
  '/synergy': typeof SynergyRoute
  '/team-convention': typeof TeamConventionRoute
  '/tedx': typeof TedxRoute
  '/tedx1': typeof Tedx1Route
  '/the': typeof TheRoute
  '/time-table-batch-of-2023-24': typeof TimeTableBatchOf202324Route
  '/upcoming-events': typeof UpcomingEventsRoute
  '/posts/test-blog': typeof PostsTestBlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission-lists'
    | '/admissions-1'
    | '/alumni'
    | '/alumni-committee'
    | '/alumni-dinner'
    | '/batch-2020-2022'
    | '/batch-2021-2023'
    | '/batch-2022-2024'
    | '/batch-2023-2025'
    | '/blog'
    | '/copy-of-batch-2023-2025'
    | '/copy-of-batch-2024-2026'
    | '/copy-of-erudition'
    | '/copy-of-home'
    | '/copy-of-marcom-cell'
    | '/copy-of-upcoming-events'
    | '/corporate-relations-team'
    | '/disco'
    | '/ecclesia'
    | '/erudition'
    | '/erudition-testimonials'
    | '/erudition1'
    | '/facilities'
    | '/faqs'
    | '/finance-cell'
    | '/ib-cell'
    | '/iisac'
    | '/linkinbio'
    | '/marcom-cell'
    | '/media-and-pr-cell'
    | '/media-coverage-form'
    | '/newsletters'
    | '/placements'
    | '/programme-brochure'
    | '/prospective-recruiters'
    | '/ravenbrain'
    | '/registration'
    | '/sports-cell'
    | '/student-body'
    | '/symposia'
    | '/synergy'
    | '/team-convention'
    | '/tedx'
    | '/tedx1'
    | '/the'
    | '/time-table-batch-of-2023-24'
    | '/upcoming-events'
    | '/posts/test-blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission-lists'
    | '/admissions-1'
    | '/alumni'
    | '/alumni-committee'
    | '/alumni-dinner'
    | '/batch-2020-2022'
    | '/batch-2021-2023'
    | '/batch-2022-2024'
    | '/batch-2023-2025'
    | '/blog'
    | '/copy-of-batch-2023-2025'
    | '/copy-of-batch-2024-2026'
    | '/copy-of-erudition'
    | '/copy-of-home'
    | '/copy-of-marcom-cell'
    | '/copy-of-upcoming-events'
    | '/corporate-relations-team'
    | '/disco'
    | '/ecclesia'
    | '/erudition'
    | '/erudition-testimonials'
    | '/erudition1'
    | '/facilities'
    | '/faqs'
    | '/finance-cell'
    | '/ib-cell'
    | '/iisac'
    | '/linkinbio'
    | '/marcom-cell'
    | '/media-and-pr-cell'
    | '/media-coverage-form'
    | '/newsletters'
    | '/placements'
    | '/programme-brochure'
    | '/prospective-recruiters'
    | '/ravenbrain'
    | '/registration'
    | '/sports-cell'
    | '/student-body'
    | '/symposia'
    | '/synergy'
    | '/team-convention'
    | '/tedx'
    | '/tedx1'
    | '/the'
    | '/time-table-batch-of-2023-24'
    | '/upcoming-events'
    | '/posts/test-blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admission-lists'
    | '/admissions-1'
    | '/alumni'
    | '/alumni-committee'
    | '/alumni-dinner'
    | '/batch-2020-2022'
    | '/batch-2021-2023'
    | '/batch-2022-2024'
    | '/batch-2023-2025'
    | '/blog'
    | '/copy-of-batch-2023-2025'
    | '/copy-of-batch-2024-2026'
    | '/copy-of-erudition'
    | '/copy-of-home'
    | '/copy-of-marcom-cell'
    | '/copy-of-upcoming-events'
    | '/corporate-relations-team'
    | '/disco'
    | '/ecclesia'
    | '/erudition'
    | '/erudition-testimonials'
    | '/erudition1'
    | '/facilities'
    | '/faqs'
    | '/finance-cell'
    | '/ib-cell'
    | '/iisac'
    | '/linkinbio'
    | '/marcom-cell'
    | '/media-and-pr-cell'
    | '/media-coverage-form'
    | '/newsletters'
    | '/placements'
    | '/programme-brochure'
    | '/prospective-recruiters'
    | '/ravenbrain'
    | '/registration'
    | '/sports-cell'
    | '/student-body'
    | '/symposia'
    | '/synergy'
    | '/team-convention'
    | '/tedx'
    | '/tedx1'
    | '/the'
    | '/time-table-batch-of-2023-24'
    | '/upcoming-events'
    | '/posts/test-blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionListsRoute: typeof AdmissionListsRoute
  Admissions1Route: typeof Admissions1Route
  AlumniRoute: typeof AlumniRoute
  AlumniCommitteeRoute: typeof AlumniCommitteeRoute
  AlumniDinnerRoute: typeof AlumniDinnerRoute
  Batch20202022Route: typeof Batch20202022Route
  Batch20212023Route: typeof Batch20212023Route
  Batch20222024Route: typeof Batch20222024Route
  Batch20232025Route: typeof Batch20232025Route
  BlogRoute: typeof BlogRoute
  CopyOfBatch20232025Route: typeof CopyOfBatch20232025Route
  CopyOfBatch20242026Route: typeof CopyOfBatch20242026Route
  CopyOfEruditionRoute: typeof CopyOfEruditionRoute
  CopyOfHomeRoute: typeof CopyOfHomeRoute
  CopyOfMarcomCellRoute: typeof CopyOfMarcomCellRoute
  CopyOfUpcomingEventsRoute: typeof CopyOfUpcomingEventsRoute
  CorporateRelationsTeamRoute: typeof CorporateRelationsTeamRoute
  DiscoRoute: typeof DiscoRoute
  EcclesiaRoute: typeof EcclesiaRoute
  EruditionRoute: typeof EruditionRoute
  EruditionTestimonialsRoute: typeof EruditionTestimonialsRoute
  Erudition1Route: typeof Erudition1Route
  FacilitiesRoute: typeof FacilitiesRoute
  FaqsRoute: typeof FaqsRoute
  FinanceCellRoute: typeof FinanceCellRoute
  IbCellRoute: typeof IbCellRoute
  IisacRoute: typeof IisacRoute
  LinkinbioRoute: typeof LinkinbioRoute
  MarcomCellRoute: typeof MarcomCellRoute
  MediaAndPrCellRoute: typeof MediaAndPrCellRoute
  MediaCoverageFormRoute: typeof MediaCoverageFormRoute
  NewslettersRoute: typeof NewslettersRoute
  PlacementsRoute: typeof PlacementsRoute
  ProgrammeBrochureRoute: typeof ProgrammeBrochureRoute
  ProspectiveRecruitersRoute: typeof ProspectiveRecruitersRoute
  RavenbrainRoute: typeof RavenbrainRoute
  RegistrationRoute: typeof RegistrationRoute
  SportsCellRoute: typeof SportsCellRoute
  StudentBodyRoute: typeof StudentBodyRoute
  SymposiaRoute: typeof SymposiaRoute
  SynergyRoute: typeof SynergyRoute
  TeamConventionRoute: typeof TeamConventionRoute
  TedxRoute: typeof TedxRoute
  Tedx1Route: typeof Tedx1Route
  TheRoute: typeof TheRoute
  TimeTableBatchOf202324Route: typeof TimeTableBatchOf202324Route
  UpcomingEventsRoute: typeof UpcomingEventsRoute
  PostsTestBlogRoute: typeof PostsTestBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming-events': {
      id: '/upcoming-events'
      path: '/upcoming-events'
      fullPath: '/upcoming-events'
      preLoaderRoute: typeof UpcomingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-table-batch-of-2023-24': {
      id: '/time-table-batch-of-2023-24'
      path: '/time-table-batch-of-2023-24'
      fullPath: '/time-table-batch-of-2023-24'
      preLoaderRoute: typeof TimeTableBatchOf202324RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the': {
      id: '/the'
      path: '/the'
      fullPath: '/the'
      preLoaderRoute: typeof TheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tedx1': {
      id: '/tedx1'
      path: '/tedx1'
      fullPath: '/tedx1'
      preLoaderRoute: typeof Tedx1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tedx': {
      id: '/tedx'
      path: '/tedx'
      fullPath: '/tedx'
      preLoaderRoute: typeof TedxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-convention': {
      id: '/team-convention'
      path: '/team-convention'
      fullPath: '/team-convention'
      preLoaderRoute: typeof TeamConventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synergy': {
      id: '/synergy'
      path: '/synergy'
      fullPath: '/synergy'
      preLoaderRoute: typeof SynergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symposia': {
      id: '/symposia'
      path: '/symposia'
      fullPath: '/symposia'
      preLoaderRoute: typeof SymposiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-body': {
      id: '/student-body'
      path: '/student-body'
      fullPath: '/student-body'
      preLoaderRoute: typeof StudentBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-cell': {
      id: '/sports-cell'
      path: '/sports-cell'
      fullPath: '/sports-cell'
      preLoaderRoute: typeof SportsCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ravenbrain': {
      id: '/ravenbrain'
      path: '/ravenbrain'
      fullPath: '/ravenbrain'
      preLoaderRoute: typeof RavenbrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospective-recruiters': {
      id: '/prospective-recruiters'
      path: '/prospective-recruiters'
      fullPath: '/prospective-recruiters'
      preLoaderRoute: typeof ProspectiveRecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme-brochure': {
      id: '/programme-brochure'
      path: '/programme-brochure'
      fullPath: '/programme-brochure'
      preLoaderRoute: typeof ProgrammeBrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters': {
      id: '/newsletters'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof NewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-coverage-form': {
      id: '/media-coverage-form'
      path: '/media-coverage-form'
      fullPath: '/media-coverage-form'
      preLoaderRoute: typeof MediaCoverageFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-and-pr-cell': {
      id: '/media-and-pr-cell'
      path: '/media-and-pr-cell'
      fullPath: '/media-and-pr-cell'
      preLoaderRoute: typeof MediaAndPrCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcom-cell': {
      id: '/marcom-cell'
      path: '/marcom-cell'
      fullPath: '/marcom-cell'
      preLoaderRoute: typeof MarcomCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkinbio': {
      id: '/linkinbio'
      path: '/linkinbio'
      fullPath: '/linkinbio'
      preLoaderRoute: typeof LinkinbioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iisac': {
      id: '/iisac'
      path: '/iisac'
      fullPath: '/iisac'
      preLoaderRoute: typeof IisacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ib-cell': {
      id: '/ib-cell'
      path: '/ib-cell'
      fullPath: '/ib-cell'
      preLoaderRoute: typeof IbCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-cell': {
      id: '/finance-cell'
      path: '/finance-cell'
      fullPath: '/finance-cell'
      preLoaderRoute: typeof FinanceCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erudition1': {
      id: '/erudition1'
      path: '/erudition1'
      fullPath: '/erudition1'
      preLoaderRoute: typeof Erudition1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erudition-testimonials': {
      id: '/erudition-testimonials'
      path: '/erudition-testimonials'
      fullPath: '/erudition-testimonials'
      preLoaderRoute: typeof EruditionTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erudition': {
      id: '/erudition'
      path: '/erudition'
      fullPath: '/erudition'
      preLoaderRoute: typeof EruditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecclesia': {
      id: '/ecclesia'
      path: '/ecclesia'
      fullPath: '/ecclesia'
      preLoaderRoute: typeof EcclesiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disco': {
      id: '/disco'
      path: '/disco'
      fullPath: '/disco'
      preLoaderRoute: typeof DiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-relations-team': {
      id: '/corporate-relations-team'
      path: '/corporate-relations-team'
      fullPath: '/corporate-relations-team'
      preLoaderRoute: typeof CorporateRelationsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-of-upcoming-events': {
      id: '/copy-of-upcoming-events'
      path: '/copy-of-upcoming-events'
      fullPath: '/copy-of-upcoming-events'
      preLoaderRoute: typeof CopyOfUpcomingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-of-marcom-cell': {
      id: '/copy-of-marcom-cell'
      path: '/copy-of-marcom-cell'
      fullPath: '/copy-of-marcom-cell'
      preLoaderRoute: typeof CopyOfMarcomCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-of-home': {
      id: '/copy-of-home'
      path: '/copy-of-home'
      fullPath: '/copy-of-home'
      preLoaderRoute: typeof CopyOfHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-of-erudition': {
      id: '/copy-of-erudition'
      path: '/copy-of-erudition'
      fullPath: '/copy-of-erudition'
      preLoaderRoute: typeof CopyOfEruditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-of-batch-2024-2026': {
      id: '/copy-of-batch-2024-2026'
      path: '/copy-of-batch-2024-2026'
      fullPath: '/copy-of-batch-2024-2026'
      preLoaderRoute: typeof CopyOfBatch20242026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy-of-batch-2023-2025': {
      id: '/copy-of-batch-2023-2025'
      path: '/copy-of-batch-2023-2025'
      fullPath: '/copy-of-batch-2023-2025'
      preLoaderRoute: typeof CopyOfBatch20232025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-2023-2025': {
      id: '/batch-2023-2025'
      path: '/batch-2023-2025'
      fullPath: '/batch-2023-2025'
      preLoaderRoute: typeof Batch20232025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-2022-2024': {
      id: '/batch-2022-2024'
      path: '/batch-2022-2024'
      fullPath: '/batch-2022-2024'
      preLoaderRoute: typeof Batch20222024RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-2021-2023': {
      id: '/batch-2021-2023'
      path: '/batch-2021-2023'
      fullPath: '/batch-2021-2023'
      preLoaderRoute: typeof Batch20212023RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-2020-2022': {
      id: '/batch-2020-2022'
      path: '/batch-2020-2022'
      fullPath: '/batch-2020-2022'
      preLoaderRoute: typeof Batch20202022RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni-dinner': {
      id: '/alumni-dinner'
      path: '/alumni-dinner'
      fullPath: '/alumni-dinner'
      preLoaderRoute: typeof AlumniDinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni-committee': {
      id: '/alumni-committee'
      path: '/alumni-committee'
      fullPath: '/alumni-committee'
      preLoaderRoute: typeof AlumniCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions-1': {
      id: '/admissions-1'
      path: '/admissions-1'
      fullPath: '/admissions-1'
      preLoaderRoute: typeof Admissions1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission-lists': {
      id: '/admission-lists'
      path: '/admission-lists'
      fullPath: '/admission-lists'
      preLoaderRoute: typeof AdmissionListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/test-blog': {
      id: '/posts/test-blog'
      path: '/posts/test-blog'
      fullPath: '/posts/test-blog'
      preLoaderRoute: typeof PostsTestBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionListsRoute: AdmissionListsRoute,
  Admissions1Route: Admissions1Route,
  AlumniRoute: AlumniRoute,
  AlumniCommitteeRoute: AlumniCommitteeRoute,
  AlumniDinnerRoute: AlumniDinnerRoute,
  Batch20202022Route: Batch20202022Route,
  Batch20212023Route: Batch20212023Route,
  Batch20222024Route: Batch20222024Route,
  Batch20232025Route: Batch20232025Route,
  BlogRoute: BlogRoute,
  CopyOfBatch20232025Route: CopyOfBatch20232025Route,
  CopyOfBatch20242026Route: CopyOfBatch20242026Route,
  CopyOfEruditionRoute: CopyOfEruditionRoute,
  CopyOfHomeRoute: CopyOfHomeRoute,
  CopyOfMarcomCellRoute: CopyOfMarcomCellRoute,
  CopyOfUpcomingEventsRoute: CopyOfUpcomingEventsRoute,
  CorporateRelationsTeamRoute: CorporateRelationsTeamRoute,
  DiscoRoute: DiscoRoute,
  EcclesiaRoute: EcclesiaRoute,
  EruditionRoute: EruditionRoute,
  EruditionTestimonialsRoute: EruditionTestimonialsRoute,
  Erudition1Route: Erudition1Route,
  FacilitiesRoute: FacilitiesRoute,
  FaqsRoute: FaqsRoute,
  FinanceCellRoute: FinanceCellRoute,
  IbCellRoute: IbCellRoute,
  IisacRoute: IisacRoute,
  LinkinbioRoute: LinkinbioRoute,
  MarcomCellRoute: MarcomCellRoute,
  MediaAndPrCellRoute: MediaAndPrCellRoute,
  MediaCoverageFormRoute: MediaCoverageFormRoute,
  NewslettersRoute: NewslettersRoute,
  PlacementsRoute: PlacementsRoute,
  ProgrammeBrochureRoute: ProgrammeBrochureRoute,
  ProspectiveRecruitersRoute: ProspectiveRecruitersRoute,
  RavenbrainRoute: RavenbrainRoute,
  RegistrationRoute: RegistrationRoute,
  SportsCellRoute: SportsCellRoute,
  StudentBodyRoute: StudentBodyRoute,
  SymposiaRoute: SymposiaRoute,
  SynergyRoute: SynergyRoute,
  TeamConventionRoute: TeamConventionRoute,
  TedxRoute: TedxRoute,
  Tedx1Route: Tedx1Route,
  TheRoute: TheRoute,
  TimeTableBatchOf202324Route: TimeTableBatchOf202324Route,
  UpcomingEventsRoute: UpcomingEventsRoute,
  PostsTestBlogRoute: PostsTestBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
